/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lowploy_tree_draco.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function PolyTree(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/assets/3d-assets/lowploy_tree_draco.gltf'
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Tree_lp_11"
          geometry={nodes.Tree_lp_11.geometry}
          material={materials['default']}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.0015}
          position={[0, -1.5, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/lowploy_tree_draco.gltf');
